const actionsType = {
  SET_BANNER: "SET_BANNER",
  SET_MOVIES_LIST: "SET_MOVIES_LIST",
  SET_CINEMAS_SYSTEM: "SET_CINEMAS_SYSTEM",
  SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  SET_THEATER_DETAIL: "SET_THEATER_DETAIL",
  SET_BOOKED_CHAIR: "SET_BOOKED_CHAIR",
};

export default actionsType;
