const actionsType = {
  SET_BANNER: "SET_BANNER",
  SET_MOVIES_LIST: "SET_MOVIES_LIST",
  SET_CINEMAS_SYSTEM: "SET_CINEMAS_SYSTEM",
  SET_MOVIE_DETAIL: "SET_MOVIE_DETAIL",
  SET_USER_PROFILE: "SET_USER_PROFILE",
  REMOVE_USER_PROFILE: "REMOVE_USER_PROFILE",
  SET_THEATER_DETAIL: "SET_THEATER_DETAIL",
  SET_BOOKING_CHAIR: "SET_BOOKING_CHAIR",
  SET_BOOKING_HISTORY: "SET_BOOKING_HISTORY",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING",
  BOOKING_COMPLETE: "BOOKING_COMPLETE",
  TAB_CHANGE_AUTO: "TAB_CHANGE_AUTO",
  TAB_CHANGE_ACTIVE: "TAB_CHANGE_ACTIVE",
  SET_FULL_MOVIE_LIST: "SET_FULL_MOVIE_LIST",
  SET_MOVIE_INFO: "SET_MOVIE_INFO",
  SET_USER_LIST: "SET_USER_LIST",
};

export default actionsType;
